Chat:
  Enabled: true
  Colors: true
  Compatibility: true
  Database: 'flatfile'
  Format: '<name>: <message>'
  Prefix:
    Air: '[Airbender] '
    Fire: '[Firebender] '
    Avatar: '[Avatar] '
    Water: '[Waterbender] '
    Earth: '[Earthbender] '
    ChiBlocker: '[Chiblocker] '
  Color:
    Avatar: DARK_PURPLE
    Air: AQUA
    Fire: RED
    Earth: GREEN
    Water: BLUE
    ChiBlocker: GRAY
Bending:
  Option:
    Bend-To-Item: false
    Use-TagAPI: false
    Reverse-Earthbending: true
    Reverse-Earthbending-Check-Time: 120000
    Firebending-Dissipate-Time: 1000
    Sea-Level: 63
    EarthBendable:
    - STONE
    - CLAY
    - COAL_ORE
    - DIAMOND_ORE
    - DIRT
    - GOLD_ORE
    - EMERALD_ORE
    - GRASS
    - GRAVEL
    - IRON_ORE
    - LAPIS_ORE
    - REDSTONE_ORE
    - SAND
    - SANDSTONE
    - GLOWING_REDSTONE_ORE
    - MYCEL
Properties:
  Spirit:
    AstralProjection:
      Cooldown: 2000
    AvatarState:
      Duration: 300000
      Cooldown: 1200000
  ChiBlocker:
    ChiBlock-Duration: 3000
    Dodge-Chance: 10.0
    Punch-Damage: 7.0
    Fall-Damage-Reduction: 1.0
    HighJump:
      Height: 1.5
      Cooldown: 5000
    Paralyze:
      Cooldown: 10000
      Duration: 2500
    RapidPunch:
      Damage: 3
      Distance: 2
      Cooldown: 3000
      Punches: 4
    SmokeBomb:
      Radius: 5
      Duration: 10
      Cooldown: 6000
    PoisonnedDart:
      Range: 16
      Damage: 2
      poison-level: 1
      Cooldown: 1500
    Dash:
      Cooldown: 6000
      Length: 1.9
      Height: 0.7
    PlasticBomb:
      Cooldown: 20000
      Radius: 2.35
      Damage: 4
  GlobalCooldown: 500
  Air:
    AirBlast:
      Speed: 25.0
      Range: 20.0
      Affecting-Radius: 2.0
      Push-Factor: 3.0
    AirBubble:
      Radius: 4
    Passive:
      Factor: 0.3
    AirShield:
      Radius: 5.0
    AirSuction:
      Speed: 25.0
      Range: 20.0
      Affecting-Radius: 2.0
      Push-Factor: 2.5
    AirSwipe:
      Damage: 5
      Range: 16.0
      Arc: 20
      Speed: 25.0
      Affecting-Radius: 2.0
      Push-Factor: 1.0
      Cooldown: 1500
    Tornado:
      Radius: 10.0
      Height: 25.0
      Range: 25.0
      Mob-Push-Factor: 1.0
      Player-Push-Factor: 1.0
    AirScooter:
      Speed: 0.675
    AirSpout:
      Height: 20.0
    AirManipulation:
      Damage: 2
      Range: 25
    Suffocate:
      Distance: 10
      Damage: 1
  Earth:
    Catapult:
      Length: 6
      Speed: 10.0
      Push: 4.0
    CompactColumn:
      Range: 20.0
      Speed: 8.0
    EarthBlast:
      Damage: 7
      Hit-Self: false
      Prepare-Range: 11.0
      Range: 20.0
      Speed: 35.0
      Revert: true
      Push: 0.3
    IronBlast:
      Damage: 9
    EarthColumn:
      Height: 6
    EarthGrab:
      Range: 15.0
      Duration: 150000
      Cooldown: 15000
    EarthPassive:
      Wait-Before-Reverse-Changes: 3000
      resistance-level: 0
    EarthTunnel:
      Max-Radius: 1.0
      Range: 9.0
      Radius: 0.25
      Interval: 30
      Revert: true
    EarthWall:
      Range: 15
      Height: 6
      Width: 6
    Collapse:
      Range: 20
      Radius: 7.0
    Tremorsense:
      Cooldown: 1000
      Max-Depth: 10
      Radius: 5
      Light-Threshold: 7
    EarthArmor:
      Duration: 60000
      Strength: 2
      Cooldown: 60000
    LavaTrain:
      Duration: 20000
      Range: 7
      Train-Width: 1
      Random-Width: 2
      Random-Chance: 0.25
      Reach-Width: 3
      Cooldown: 10000
    LavaBlast:
      Range: 15
      ChargeTime: 1000
      Damage: 10
  Fire:
    FireBlast:
      Range: 25.0
      Speed: 15.0
      Push: 0.3
      Radius: 2.0
      Cooldown: 1300
      Damage: 6
      Dissipates: false
    ArcOfFire:
      Arc: 20
      Range: 9
    RingOfFire:
      Range: 7
    Extinguish:
      Range: 20.0
      Radius: 7.0
    Fireball:
      Cooldown: 300000
      Speed: 0.3
    FireJet:
      Speed: 0.7
      Duration: 1500
      CoolDown: 6000
    FireStream:
      Speed: 15.0
    WallOfFire:
      Range: 4
      Height: 4
      Width: 4
      Duration: 5000
      Damage: 9
      Interval: 500
      Cooldown: 7500
    HeatMelt:
      Range: 15
      Radius: 5
    Illumination:
      Range: 5
    Lightning:
      Damage: 10
      Warmup: 4000
      Range: 50
      Miss-Chance: 5.0
    FireBlade:
      sharpness-level: 1
      fireaspect-level: 2
      Duration: 40
      strength-level: 0
      Cooldown: 40000
    Combustion:
      Damage: 6
      Range: 20
      ChargeTime: 2000
      Cooldown: 2000
      Radius: 1.5
      Explosion-Radius: 3.0
      Inner-Radius: 3.0
    Day-Power-Factor: 1.1
  Water:
    Bloodbending:
      Throw-Factor: 1.0
      Range: 9
      Max-Duration: 10
      Cooldown: 5000
    FreezeMelt:
      Range: 20
      Radius: 3
      Depth: 1
    HealingWaters:
      Radius: 5.0
      Interval: 750
    Plantbending:
      Regrow-Time: 180000
    WaterManipulation:
      Damage: 7
      Range: 22.0
      Speed: 35.0
      Push: 0.3
    WaterSpout:
      Height: 18
      Rotation-Speed: 4
    WaterWall:
      Range: 5.0
      Radius: 2.0
    Wave:
      Radius: 3.0
      Horizontal-Push-Force: 1.0
      Vertical-Push-Force: 0.2
    FastSwimming:
      Factor: 0.7
    IceSpike:
      Cooldown: 2000
      Damage: 4
      Range: 20
      ThrowingMult: 0.7
      AreaCooldown: 3000
      AreaDamage: 2
      AreaRadius: 6
      AreaThrowingMult: 1.0
    Torrent:
      Damage: 6
      DeflectDamage: 2
    OctopusForm:
      Damage: 5
    IceSwipe:
      Damage: 4
      Range: 25
      Speed: 25.0
      Push-Factor: 1.0
      Cooldown: 1500
    Night-Power-Factor: 1.5
